In [5]:
from google.colab import files
import os
import zipfile

In [6]:
width, height = 256, 256

In [7]:
! pip install -q kaggle


In [8]:
#files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"larada","key":"2d01da7eff2b426ae0379bf5729939e5"}'}

In [9]:
! mkdir ~/.kaggle 
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets list

ref                                                         title                                              size  lastUpdated          downloadCount  
----------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------  
gpreda/reddit-vaccine-myths                                 Reddit Vaccine Myths                              235KB  2021-09-15 20:16:36          12285  
crowww/a-large-scale-fish-dataset                           A Large Scale Fish Dataset                          3GB  2021-04-28 17:03:01           7441  
imsparsh/musicnet-dataset                                   MusicNet Dataset                                   22GB  2021-02-18 14:12:19           3035  
dhruvildave/wikibooks-dataset                               Wikibooks Dataset                                   2GB  2021-07-03 18:37:20           2905  
promptcloud/careerbuilder-job-listing-2020                  Careerbuilder Jo

# Download Datasets

# BIG 2015

In [ ]:
! kaggle competitions download -c malware-classification

403 - Forbidden


In [ ]:
local_zip = '/content/BIG.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/BIG2015')
zip_ref.close()

# MalImg

In [ ]:
! kaggle datasets download -d keerthicheepurupalli/malimg-dataset9010

 99% 1.20G/1.21G [00:11<00:00, 129MB/s]
100% 1.21G/1.21G [00:11<00:00, 113MB/s]


In [ ]:
local_zip = '/content/malimg-dataset9010.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/MalImg')
zip_ref.close()

In [ ]:
import os
from os.path import join as pjoin
import cv2
import numpy as np

data_dir  = '/content/MalImg/dataset_9010/dataset_9010/malimg_dataset/train'
binary_dir = '/content/bin_MalImg/train'


def savefile(guy,i,binary_file):
    save_dir = pjoin(binary_dir, guy)  # the save address
    if not os.path.exists(save_dir):  # if the save address doesn't exsit, create
        os.makedirs(save_dir)
    name_binary = "{}/{}.npy".format(save_dir,i[:-4])#the name of .npy file
    np.save(name_binary,binary_file)


def load_data(data_dir):
    for guy in os.listdir(data_dir):#read the name of img_family in the data_dir
        family_dir = pjoin(data_dir,guy)#the malware family document direciton
        for i in os.listdir(family_dir):#read the img name in this family
            img_dir= pjoin(family_dir,i)#img address
            img = cv2.imread(img_dir,cv2.IMREAD_GRAYSCALE)#read the img
            img_1D = img.flatten()
            savefile(guy,i,img_1D)

load_data(data_dir)

FileNotFoundError: ignored

# Goodware dataset

In [ ]:
!wget --no-check-certificate \
     https://download.wetransfer.com/eugv/48b7cd3775c1a521c8f7d03ab991781720210912103653/e95f4256bafa9735bcec91838495a3e2f6b4c9f3/executables.zip?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE0NTQ4MDUsImV4cCI6MTYzMTQ1NTQwNSwidW5pcXVlIjoiNDhiN2NkMzc3NWMxYTUyMWM4ZjdkMDNhYjk5MTc4MTcyMDIxMDkxMjEwMzY1MyIsImZpbGVuYW1lIjoiZXhlY3V0YWJsZXMuemlwIiwid2F5YmlsbF91cmwiOiJodHRwOi8vc3Rvcm0taW50ZXJuYWwuc2VydmljZS5ldS13ZXN0LTEud2V0cmFuc2Zlci5uZXQvYXBpL3dheWJpbGxzP3NpZ25lZF93YXliaWxsX2lkPWV5SmZjbUZwYkhNaU9uc2liV1Z6YzJGblpTSTZJa0pCYUhOTGQyWTRiMGhvWVNJc0ltVjRjQ0k2SWpJd01qRXRNRGt0TVRKVU1UUTZNRE02TWpVdU1EQXdXaUlzSW5CMWNpSTZJbmRoZVdKcGJHeGZhV1FpZlgwLS05ZDczMmI0ODNiY2ZiZDM0N2Y1YzgyMWFkY2Q1YTFmZmM1ZmU1ZjRlZmZiNTE5YzhjYTUxOGYyYzNkM2I3NzJmIiwiZmluZ2VycHJpbnQiOiJlOTVmNDI1NmJhZmE5NzM1YmNlYzkxODM4NDk1YTNlMmY2YjRjOWYzIiwiY2FsbGJhY2siOiJ7XCJmb3JtZGF0YVwiOntcImFjdGlvblwiOlwiaHR0cDovL2Zyb250ZW5kLnNlcnZpY2UuZXUtd2VzdC0xLndldHJhbnNmZXIubmV0L3dlYmhvb2tzL2JhY2tlbmRcIn0sXCJmb3JtXCI6e1widHJhbnNmZXJfaWRcIjpcIjQ4YjdjZDM3NzVjMWE1MjFjOGY3ZDAzYWI5OTE3ODE3MjAyMTA5MTIxMDM2NTNcIixcImRvd25sb2FkX2lkXCI6MTMwNjI1ODAyMzZ9fSJ9.F1Emfuf53pGzLscZ8ZfcD66WpG8G0yQq1OsB41RVqfA&cf=y

The name is too long, 999 chars total.
Trying to shorten...
New name is executables.zip?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE0NTQ4MDUsImV4cCI6MTYzMTQ1NTQwNSwidW5pcXVlIjoiNDhiN2NkMzc3NWMxYTUyMWM4ZjdkMDNhYjk5MTc4MTcyMDIxMDkxMjEwMzY1MyIsImZpbGVuYW1lIjoiZXhlY3V0YWJsZXMuemlwIiwid2F5YmlsbF91cmwiOiJodHRwOi8vc.
--2021-09-14 12:49:17--  https://download.wetransfer.com/eugv/48b7cd3775c1a521c8f7d03ab991781720210912103653/e95f4256bafa9735bcec91838495a3e2f6b4c9f3/executables.zip?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE0NTQ4MDUsImV4cCI6MTYzMTQ1NTQwNSwidW5pcXVlIjoiNDhiN2NkMzc3NWMxYTUyMWM4ZjdkMDNhYjk5MTc4MTcyMDIxMDkxMjEwMzY1MyIsImZpbGVuYW1lIjoiZXhlY3V0YWJsZXMuemlwIiwid2F5YmlsbF91cmwiOiJodHRwOi8vc3Rvcm0taW50ZXJuYWwuc2VydmljZS5ldS13ZXN0LTEud2V0cmFuc2Zlci5uZXQvYXBpL3dheWJpbGxzP3NpZ25lZF93YXliaWxsX2lkPWV5SmZjbUZwYkhNaU9uc2liV1Z6YzJGblpTSTZJa0pCYUhOTGQyWTRiMGhvWVNJc0ltVjRjQ0k2SWpJd01qRXRNRGt0TVRKVU1UUTZNRE02TWpVdU1EQXdXaUlzSW5CMWNpSTZJbmRoZVdKcGJHeGZhV1FpZlgwLS05ZDczMmI0ODNiY2ZiZDM0N2Y1YzgyMWFkY2Q1Y

In [ ]:
local_zip = '/content/executables.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/goodware')
zip_ref.close()

# Data preprocessing functions

In [10]:
# ref: https://github.com/ncarkaci/binary-to-image
import numpy as np
import os, math
import argparse
from PIL import Image 


In [11]:
def defineColorMap():
  rows  = 256
  columns = 256
  min = 0 
  max = 256
  step = 2
  colormap = np.random.randint(min, max, size=rows * columns, dtype='l')
  colormap.resize(rows,columns)
  print(colormap)
  print("\n\n ",colormap.shape)
  return colormap

In [12]:
'''colormap = defineColorMap()
R_colormap = defineColorMap()
G_colormap = defineColorMap()
B_colormap = defineColorMap()'''


'colormap = defineColorMap()\nR_colormap = defineColorMap()\nG_colormap = defineColorMap()\nB_colormap = defineColorMap()'

In [13]:
def readBytes (filename):
  img_bin_data = []
  with open(filename, 'rb') as file:
     #this sintax is to be read as "with the output of the function open considered as a file"
     # wb as in read binary
    while True:
      # as long as we can read one byte
      b = file.read(1)
      if not b:
        break
      img_bin_data.append(int.from_bytes(b, byteorder='big'))
  return img_bin_data

In [14]:
def readBytes_fromNumpy (filename):
  return np.load(filename)    

In [ ]:
#img_bin_data = readBytes('/content/logounirc.png')
#print(img_bin_data)

In [ ]:
#img_bin_data = readBytes_fromNumpy('/content/123.npy')
#print(img_bin_data)

In [15]:
from itertools import zip_longest
def grouper(iterable, n, fillvalue=None):
  "Collect data into fixed-length chunks or blocks"
  # grouper('ABCDEFG', 3, 'x') --> ABC DEF Gxx
  args = [iter(iterable)] * n
  return zip_longest(fillvalue = fillvalue, *args)
 

In [16]:
def to1DArray_grayscale(img_bin_data):
  pixel_array = []
  
  for x, y in grouper(img_bin_data, 2) :
    
    new_pixel = colormap[x][y]
    
    pixel_array.append(new_pixel)
    
  return pixel_array  

In [ ]:
#grayscale_array = to1DArray_grayscale(img_bin_data)

In [17]:
def to1DArray_RGB(img_bin_data):
  pixel_array = []
  for x, y in grouper(img_bin_data, 2) :
    pixel_array.append((R_colormap[x][y], G_colormap[x][y], B_colormap[x][y]))
    #print(pixel_array[index])
  return pixel_array  

In [ ]:
#RGB_array = to1DArray_RGB(img_bin_data)

In [18]:
def saveImg (filename, data, size, img_type):
  try:
    image = Image.new(img_type, size)
    #tuples = [tuple(x) for x in data]
    #image.putdata(tuples)
    image.putdata(data)
    '''ref : https://stackoverflow.com/questions/68642888/issues-converting-rgb-to-image-with-correct-size'''
    ''' ref: https://github.com/ncarkaci/binary-to-image
    setup output filename
    dirname     = os.path.dirname(filename)
    name, _     = os.path.splitext(filename)
    name        = os.path.basename(name)
    imagename   = dirname + os.sep + img_type + os.sep + name + '_'+img_type+ '.png'
    os.makedirs(os.path.dirname(imagename), exist_ok=True)'''
    image.save(filename)
    # print('The file', filename, 'saved.')
  except Exception as err:
    print(err)

In [ ]:
#saveImg('/content/output.png', grayscale_array, (512,512),'L')

In [ ]:
#saveImg('/content/outputt.png', RGB_array, (512,512),'RGB')


In [19]:
def findMax(matrix):
  max = 0
  for i in range(0,256):
    for j in range(0,256):
      if matrix[i][j]>max:
        max =  matrix[i][j]
  return int(max)

In [20]:
def generateMarkovImg(binary_data):
  # input B (binary_data) = {b1, b2, b3...bn} is a set where bi represents the decimal value of a byte.
  # TM[i][j] represents the probability that byte bi is followed by bj
  TM = np.zeros((256,256))
  S = np.zeros((256,1))
  L = len(binary_data)
  #we determine the frequency of occurrence of byte bi followed by bi+1 and bi followed by bk where 0 ≤ k ≤ 255. 
  i=0
  while i < L-1:
    r = binary_data[i]
    
    c = binary_data[i+1]
    
    TM[r][c] = TM[r][c] +1
    S[r] = S[r] + 1
    
    i = i+1

  i = 0
  j = 0
  #compute the probability that byte bi is followed by bi+1
  while i < 256:
    rs = S[i]
    while j < 256:
      TM[i][j] = TM[i][j]/rs
      j = j+1
    i = i+1

  print("TM shape", TM.shape)
  MP = findMax(TM)
  print('max',MP)
  i = 0
  j = 0
  M =  np.zeros((256,256))
  # compute pixels in Markov image
  while i < 256:
    while j < 256:
      
      p = (TM[i][j]*(255/MP))%256
      M[i][j] = p
      j = j+1
    i = i+1
  print(M)
  return M
  #Output: M = {m1, m2, m3...mn} is a set where mi represents a pixel value in Markov image.


In [ ]:
#saveImg('/content/outputtt.png', generateMarkovImg(img_bin_data), (512,512),'L')

In [ ]:
import numpy as np
import cv2 
import matplotlib.pyplot as plt
'''
ksize = 3 # kernel size
sigma = 3 # standard deviation
theta = 180 # orientation of the Gabor function
lambd = 180 # width of the strips of the Gabor function
gamma = 0.5 # aspect ratio
psi = 0 # phase offset
ktype = ktype=cv2.CV_32F # 	Type of filter coefficients. It can be CV_32F or CV_64F . ?? not specified in the paper

# ref: https://docs.opencv.org/3.4/d4/d86/group__imgproc__filter.html#gae84c92d248183bd92fa713ce51cc3599
gabor_kernel = cv2.getGaborKernel((ksize, ksize), sigma, theta, lambd, gamma, psi, ktype=cv2.CV_32F)

plt.imshow(gabor_kernel)'''

In [ ]:
'''image = cv2.imread('/content/output.png') # reading image

image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(image, cmap='gray') '''


"image = cv2.imread('/content/output.png') # reading image\n\nimage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\nplt.imshow(image, cmap='gray') "

In [ ]:
filtered_image = cv2.filter2D(image, cv2.CV_8UC3, gabor_kernel)
plt.imshow(filtered_image, cmap='gray') 

# Data preprocessing

In [21]:
colormap = defineColorMap()
R_colormap = defineColorMap()
G_colormap = defineColorMap()
B_colormap = defineColorMap()

[[157 192 179 ... 194 127  91]
 [ 77  17  14 ...  62  47  90]
 [209  81 251 ... 152  50 220]
 ...
 [ 97 144 225 ... 128  52 129]
 [ 18 101  22 ...  62  57  93]
 [ 57  13  34 ... 208  31 113]]


  (256, 256)
[[170  45 102 ... 128 177  18]
 [145 232 170 ... 223 157 188]
 [216  43  92 ...   4 213 223]
 ...
 [ 56 218 203 ... 106  47  14]
 [248   1  78 ...  20 145  56]
 [207  77 177 ... 202 190  61]]


  (256, 256)
[[ 50 199  61 ... 252   3 185]
 [ 22  79  52 ... 154 212 146]
 [181 136 200 ...  84 193  42]
 ...
 [223 143 133 ...  94 150   6]
 [190   5  85 ... 133 183  68]
 [129 116  38 ... 222  58 202]]


  (256, 256)
[[ 45  13  17 ...  34  50 137]
 [164  57 196 ... 121 104 160]
 [195 120  41 ... 158 171 117]
 ...
 [ 69  94 125 ... 157  95  12]
 [151 236  47 ... 250 149  27]
 [195 211 233 ...   1  14 132]]


  (256, 256)


In [22]:
from pathlib import Path
Path("/content/dataset/Train").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/GRAY/m_greyscale").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/GRAY/b_greyscale").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/RGB/m_rgb").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/RGB/b_rgb").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/MARKOV/b_markov").mkdir(parents=True, exist_ok=True)
Path("/content/dataset/Train/MARKOV/b_markov").mkdir(parents=True, exist_ok=True)
Path('/content/data/dataset/training_set/cani/').mkdir(parents=True, exist_ok=True)
Path('/content/data/dataset/training_set/gatti/').mkdir(parents=True, exist_ok=True)
Path('/content/data/dataset/test_set/cani/').mkdir(parents=True, exist_ok=True)
Path('/content/data/dataset/test_set/gatti/').mkdir(parents=True, exist_ok=True)


In [23]:
# save numpy array as npy file
from numpy import asarray
from numpy import save

save('/content/colormap.npy', colormap)
save('/content/R_colormap.npy', R_colormap)
save('/content/G_colormap.npy', G_colormap)
save('/content/B_colormap.npy', B_colormap)

In [ ]:
dataset_dir = '/content/goodware/executables'
dataset_dest_dir = '/content/dataset/Train'
os.chdir(dataset_dir)
for item in os.listdir(dataset_dir):
  filename = dataset_dir + '/' + item
  print(filename)
  
  img_bin_data = readBytes(item) 
  print(len(img_bin_data))
  #img_bin_data = readBytes_fromNumpy('/content/123.npy')
  
  grayscale_array = to1DArray_grayscale(img_bin_data)
  # print(grayscale_array)
  dest = dataset_dest_dir+'/GRAY/b_greyscale/'+item[:-4]+".jpg"
  saveImg(dest, grayscale_array, (width, height), 'L')
  
  ''' 
  RGB_array = to1DArray_RGB(img_bin_data)
  dest = dataset_dest_dir+'/rgb/'+item[:-4]+".jpg"
  saveImg(dest, RGB_array, (width, height), 'RGB')
  dest = dataset_dest_dir+'/MARKOV/'+item[:-4]+".jpg"
  saveImg('dest', generateMarkovImg(img_bin_data), (width, height), 'L')'''


FileNotFoundError: ignored

# REPLACEMENT DS DA ELIMINARE

In [24]:
! kaggle datasets download -d chetankv/dogs-cats-images

 97% 422M/435M [00:03<00:00, 136MB/s]
100% 435M/435M [00:03<00:00, 117MB/s]


In [25]:
local_zip = '/content/dogs-cats-images.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/data')
zip_ref.close()

In [27]:
! mv /content/data/dataset/training_set/dogs /content/data/dataset/training_set/cani
! mv /content/data/dataset/training_set/cats /content/data/dataset/training_set/gatti

In [28]:
! mv /content/data/dataset/test_set/dogs /content/data/dataset/test_set/cani
! mv /content/data/dataset/test_set/cats /content/data/dataset/test_set/gatti

# CONVERT DATA TO IMAGES

In [ ]:
dataset_dir = '/content/bin_MalImg/train'
dataset_dest_dir = '/content/dataset/Train'
os.chdir(dataset_dir)
for child_dir in os.listdir(dataset_dir):
  current = dataset_dir+'/'+child_dir
  os.chdir(current)
  print(child_dir)
  for item in os.listdir(current):
    filename = dataset_dir + '/' + item
    print(filename)
    
    #img_bin_data = readBytes(item) 
    img_bin_data = readBytes_fromNumpy(item)
    print(len(img_bin_data))
    
    grayscale_array = to1DArray_grayscale(img_bin_data)
    # print(grayscale_array)
    # RGB_array = to1DArray_RGB(img_bin_data)
    dest = dataset_dest_dir+"/GRAY/m_greyscale/"+item[:-4]+".jpg"
    saveImg(dest, grayscale_array, (width, height), 'L')
    
   
    ''' 
    RGB_array = to1DArray_RGB(img_bin_data)
    dest = dataset_dest_dir+'/rgb/'+item[:-4]+".jpg"
    saveImg(dest, RGB_array, (width, height), 'RGB')
    dest = dataset_dest_dir+'/MARKOV/'+item[:-4]+".jpg"
    saveImg('dest', generateMarkovImg(img_bin_data), (width, height), 'L')'''
  os.chdir(dataset_dir)
  

FileNotFoundError: ignored

In [ ]:
dataset_dir = '/content/BIG2015'
dataset_dest_dir = '/content/joinedMalImg'
os.chdir(dataset_dir)
for item in os.listdir(dataset_dir):
  img_bin_data = readBytes(item)
  #img_bin_data = readBytes_fromNumpy('/content/123.npy')
  grayscale_array = to1DArray_grayscale(img_bin_data)
  RGB_array = to1DArray_RGB(img_bin_data)
  dest = dataset_dest_dir+"/RGB/"+item
  saveImg(dest, grayscale_array, (width, height), 'L')
  ''' dest = dataset_dest_dir+"/Gray/"+item
  saveImg(dest, RGB_array, (width, height), 'RGB')
  dest = dataset_dest_dir+"/Markov/"+item
  saveImg('dest', generateMarkovImg(img_bin_data), (width, height), 'L')'''


# Data Uploader class - UPDATED

In [30]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import os, os.path

class UploadData():
  def __init__(self):
    #TRAINING_DIRECTORY = '/content/dataset/Train/GRAY'
    #TRAINING_MAL_DIRECTORY = '/content/dataset/Train/GRAY/m_greyscale/'
    #TRAINING_BEN_DIRECTORY = '/content/dataset/Train/GRAY/b_greyscale/'
    
    #TEST_MAL_DIRECTORY = '/content/dataset/Train/GRAY/m_greyscale/'
    #TEST_BEN_DIRECTORY = '/content/dataset/Train/GRAY/b_greyscale/'
    
    self.TRAINING_MAL_DIRECTORY = '/content/data/dataset/training_set/gatti/'
    self.TRAINING_BEN_DIRECTORY = '/content/data/dataset/training_set/cani/'
    
    self.TEST_MAL_DIRECTORY = '/content/data/dataset/test_set/gatti/'
    self.TEST_BEN_DIRECTORY = '/content/data/dataset/test_set/cani/'
    # path joining version for other paths
    
    self.mal_train_size = len([name for name in os.listdir(self.TRAINING_MAL_DIRECTORY+'cats') if os.path.isfile(os.path.join(self.TRAINING_MAL_DIRECTORY+'cats', name))])
    self.ben_train_size = len([name for name in os.listdir(self.TRAINING_BEN_DIRECTORY+'dogs') if os.path.isfile(os.path.join(self.TRAINING_BEN_DIRECTORY+'dogs', name))])
    self.mal_test_size = len([name for name in os.listdir(self.TEST_MAL_DIRECTORY+'cats') if os.path.isfile(os.path.join(self.TEST_MAL_DIRECTORY+'cats', name))])
    self.ben_test_size = len([name for name in os.listdir(self.TEST_BEN_DIRECTORY+'dogs') if os.path.isfile(os.path.join(self.TEST_BEN_DIRECTORY+'dogs', name))])
    
    self.COLOR_MODE = 'grayscale'
    self.IMAGE_HEIGHT = 256
    self.IMAGE_WIDTH = 256
    self.BATCH_SIZE = 32
    self.VAL_SPLIT = 0.15
    self.SEED = 1337
    self.trian_mal_lbls = [1] * self.mal_train_size
    self.trian_ben_lbls = [0] * self.ben_train_size
    self.test_mal_lbls = [1] * self.mal_test_size
    self.test_ben_lbls = [0] * self.ben_test_size


  '''def __init__(self):
  training_mal_set,vali_mal_set = self.upload_mal_set()
  training_ben_set,vali_ben_set = self.upload_ben_set()
  training_set,vali_set = self.upload_set()'''

  def upload_train_mal_set(self):
    training_mal_set = keras.preprocessing.image_dataset_from_directory(
            self.TRAINING_MAL_DIRECTORY,
            labels = self.trian_mal_lbls ,
            label_mode = 'int',
            color_mode=self.COLOR_MODE,
            validation_split=self.VAL_SPLIT,
            subset='training',
            seed=self.SEED,
            interpolation="area",
            batch_size=self.BATCH_SIZE,
            image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
            shuffle=True
    )

    val_mal_set = keras.preprocessing.image_dataset_from_directory(
      self.TRAINING_MAL_DIRECTORY,
      labels = self.trian_mal_lbls ,
      label_mode = 'int', 
      color_mode=self.COLOR_MODE,
      subset='validation',
      validation_split=self.VAL_SPLIT,
      seed=self.SEED,
      interpolation="area",
      batch_size=self.BATCH_SIZE,
      image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
      shuffle=True
    )
    return training_mal_set, val_mal_set

  def upload_train_ben_set(self):
    training_ben_set = keras.preprocessing.image_dataset_from_directory(
      self.TRAINING_BEN_DIRECTORY,            
      labels = self.trian_ben_lbls,
      label_mode = 'int',
      color_mode=self.COLOR_MODE,
      validation_split=self.VAL_SPLIT,
      subset='training',
      seed=self.SEED,
      interpolation="area",
      batch_size=self.BATCH_SIZE,
      image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
      shuffle=True,
    )
    val_ben_set = keras.preprocessing.image_dataset_from_directory(
      self.TRAINING_BEN_DIRECTORY,
      labels= self.trian_ben_lbls,
      label_mode="int",
      color_mode=self.COLOR_MODE,
      validation_split=self.VAL_SPLIT,
      subset='validation',
      seed=self.SEED,
      interpolation="area",
      batch_size=self.BATCH_SIZE,
      image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
      shuffle=True
    )
    return training_ben_set, val_ben_set

  def upload_training_set(self, training_ben_set, vali_ben_set, training_mal_set, val_mal_set):
    training_set = training_ben_set.concatenate(training_mal_set)
    training_set = training_set.unbatch()
    training_set = training_set.shuffle(int((1-self.VAL_SPLIT)*(float(self.ben_train_size+self.mal_train_size))))
    training_set = training_set.batch(self.BATCH_SIZE)

    val_set = vali_ben_set.concatenate(val_mal_set)
    val_set = val_set.unbatch()
    val_set = val_set.shuffle(int((self.VAL_SPLIT)*(float(self.ben_train_size+self.mal_train_size))))
    val_set = val_set.batch(self.BATCH_SIZE)
    return training_set, val_set



  def upload_test_mal_set(self):
    test_mal_set = keras.preprocessing.image_dataset_from_directory(
            self.TEST_MAL_DIRECTORY,
            labels = self.test_mal_lbls ,
            label_mode = 'int',
            color_mode=self.COLOR_MODE,
            seed=self.SEED,
            interpolation="area",
            batch_size=self.BATCH_SIZE,
            image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
            shuffle=True
    )
    return test_mal_set

  def upload_test_ben_set(self):
    test_ben_set = keras.preprocessing.image_dataset_from_directory(
            self.TEST_BEN_DIRECTORY,
            labels = self.test_ben_lbls ,
            label_mode = 'int',
            color_mode=self.COLOR_MODE,
            seed=self.SEED,
            interpolation="area",
            batch_size=self.BATCH_SIZE,
            image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
            shuffle=True
    )
    return test_ben_set

  def upload_test_set(self, test_ben_set, test_mal_set):
    test_set = test_ben_set.concatenate(test_mal_set)
    test_set = test_set.unbatch()
    test_set = test_set.shuffle(int((1-self.VAL_SPLIT)*(float(self.ben_test_size+self.mal_test_size))))
    test_set = test_set.batch(self.BATCH_SIZE)
    return test_set




    # how to get the dataset:    
    # https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/images.ipynb?hl=zh-tw#scrollTo=ucMoYase6URl
  def shuffle_nomalize(self, mixdata_set, mal_set, ben_set):
    AUTOTUNE = tf.data.AUTOTUNE
    mixdata_ds = mixdata_set.cache().shuffle(11929).prefetch(buffer_size=AUTOTUNE)
    mal_ds = mal_set.cache().shuffle(11929).prefetch(buffer_size=AUTOTUNE)
    ben_ds = ben_set.cache().shuffle(11929).prefetch(buffer_size=AUTOTUNE)
    # test_ds = test_set.cache().shuffle(11929).prefetch(buffer_size=AUTOTUNE)
    # validation_ds = validation_set.cache().prefetch(buffer_size=AUTOTUNE)

    # The RGB channel values are in the [0, 255] range. This is not ideal for a neural network;
    #  in general you should seek to make your input values small.
    #  Here, you will standardize values to be in the [0, 1] range by using the tf.keras.layers.experimental.preprocessing.Rescaling layer.
    normalization_layer = tf.keras.layers.experimental.preprocessing.Rescaling(1. / 255)

    normalized_ds = mixdata_ds.map(lambda x, y: (normalization_layer(x), y))
    normalized_mal_ds = mal_ds.map(lambda x, y: (normalization_layer(x), y))
    normalized_ben_ds = ben_ds.map(lambda x, y: (normalization_layer(x), y))
    # normalized_test_ds = test_ds.map(lambda x, y: (normalization_layer(x), y))
    # normalized_validatioin_ds = validation_ds.map(lambda x, y: (normalization_layer(x), y))

    return normalized_ds, normalized_mal_ds, normalized_ben_ds

    

  

In [34]:
uploader = UploadData()
cats_train, cats_val = uploader.upload_train_mal_set()
cats_test =uploader.upload_test_mal_set()


Found 4000 files belonging to 1 classes.
Using 3400 files for training.
Found 4000 files belonging to 1 classes.
Using 600 files for validation.
Found 1000 files belonging to 1 classes.


In [35]:
dogs_train, dogs_val = uploader.upload_train_ben_set()

Found 4000 files belonging to 1 classes.
Using 3400 files for training.
Found 4000 files belonging to 1 classes.
Using 600 files for validation.


In [33]:
for img_batch_cat,img_batch_dog in zip(cats_train,dogs_train):
 #print("mal_batch")
 #print(img_batch_cat)
 print("ben_batch")
 #print(img_batch_dog)
 break
 #images,label = img_batch_mal

ben_batch


In [36]:
mixed_train, mixed_val = uploader.upload_training_set(dogs_train, dogs_val,cats_train, cats_val)

In [37]:
from matplotlib.pyplot import figure, imshow, axis
irra=0

for c_batch in mixed_train:
  imgsa, lblsa = c_batch 
  print(len(lblsa))
  # for i in range(0,20):
  #   figure_1a = figure(figsize=(30, 30), dpi=100)
  #   subplota=figure_1a.add_subplot(16,16,3)
  #   #print(lblsa[i])
  #   imshow(imgsa[i].numpy().astype("uint8").squeeze())
  # #irra = irra+1
  # #print(irra)
  break

32


# Blackbox detector 

In [38]:
import numpy as np

import tensorflow as tf;
from tensorflow import keras;
from tensorflow.keras import layers, models, applications, optimizers, losses, metrics
from keras.callbacks import *
import pandas
import matplotlib.pyplot as plt


class MalwareDetectionModels:
    TRAINING_DATA_DIRECTORY = '/content/data/dataset/training_set'
    TEST_DATA_DIRECTORY = '/content/data/dataset/test_set'
    COLOR_MODE = 'grayscale'
    IMAGE_HEIGHT = 256
    IMAGE_WIDTH = 256
    BATCH_SIZE = 10
    SEED = 1337

    SEED = 1337

    def __init__(self, img_w, img_h, model_name,training_set, validation_set):
        self.image_width = img_w
        self.image_height = img_h
        self.model = None
        if model_name == "M1":
            self.model = self.bulid_m1()
            self.epochs = 50
            self.rate = 0.000075
        elif model_name == "M2":
            self.model = self.bulid_m2()
            self.epochs = 50
            self.rate = 0.00001
        elif model_name == "M3":
            '''  In M-3, initially, each input image has to go through three convolution layers of 32 neurons each.
             Then it has to go through a max pooling layer and finally through a fully connected layer of 16384 neurons. 
             It executed for 200 epochs, with a batch size of 32, and a learning rate of 0.0001.'''
            self.model = self.bulid_m3()
            self.epochs = 200
            self.batch_size = 32
            self.rate = 0.01
        elif model_name == "M4":
            self.model = self.bulid_m4()
            self.epochs = 120
            self.rate = 0.01
        elif model_name == "M5":
            # M-5 (convolution followed by global pool and a fully connected layer) has again poor performances. T
            self.model = self.bulid_m5()
            self.epochs = 50
            self.rate = 0.01
        elif model_name == "M6":
            self.model = self.bulid_m6()
            self.epochs = 50
            self.rate = 0.01
        elif model_name == "M7":
            self.model = self.bulid_m7()
            self.epochs = 250
            self.rate = 0.01
        elif model_name == "M8":
            self.model = self.bulid_m8()
            self.epochs = 200
            self.rate = 0.01
        elif model_name == "M9":
            self.model = self.bulid_m9()
            self.epochs = 30
            self.rate = 0.0001
        elif model_name == "M10":
            '''  Here, in the case of M-10 (VGG3 with dropout) the network topology is VGG3 
            followed by three fully connected layers with 1024, 2048 and 4096 respectively. 
            Hyperparameters are leraning rate of 0.0001 and batch size of 64.'''
            self.model = self.bulid_m10()
            self.epochs = 30
            self.rate = 0.0001
        elif model_name == "M11":
            '''
            Filter size of convolution layer used is 3×3 for all the models.
      
            Its architecture is composed of VGG3 followed by three fully connected layers of 4096 neurons each.
             In this model dropout rates of 0.2, 0.2, 0.3, and batch normalization were included between 
             the convolutionpooling layers of VGG3. In addition, same dropout rates and batch normalization 
             were added in between fully connected layers.
      
            for M-11 (VGG3 with dropout and batch normalization) were 30 epochs, batch-size of 64 and a learning
            rate of 0.0001 on Dataset-I while the number of epochs were increased to 200 for M-11 (VGG3 with dropout and batch normalization) on Dataset-II
            '''
            '''model M-11 (VGG3 with dropout and batch normalization) reports high performance 
            measures with a rise of 0.89% and 1.83% in F-measure compared to the model M-11 
            (VGG3 with dropout and batch normalization) generated using RGB images of Dataset-I 
            and Dataset-II respectively. The model M-11 (VGG3 with dropout and batch normalization) 
            was executed for 50 epochs with dropout rates 0.1, 0.2, 0.3 and learning rate 0.0001 on Dataset-I. For Dataset-II the dropouts were 0.1, 0.2, 0.3 with a learning rate of 0.000007. However, the epochs remained the same.'''
            self.batch_size = 64
            self.model = self.bulid_m11()
            self.epochs = 5
            self.rate = 0.0001
        elif model_name == "M12":
            ''' ResNet-50 along with three fully connected layers of 1024, 512 and 256 neurons.'''
            self.model = self.bulid_m12()
            self.epochs = 30
            self.rate = 0.0001

        self.define_callbacks()
        self.history = self.train_bb_detector(training_set, validation_set)
        # self.evaluate_bb_detector()
        # self.plot_history()

    def bulid_m1(self):
        m1 = models.Sequential()
        # m1.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Conv + Pool + Dense +Dense
        m1.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 1)))
        m1.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m1.add(layers.MaxPooling2D(pool_size=2))
        m1.add(layers.Flatten())  # if it is not flattened, only the last layer can be fed into the dense
        m1.add(layers.Dense(1024, activation='relu'))
        m1.add(layers.Dense(2, activation='relu'))
        return m1

    def bulid_m2(self):
        m2 = models.Sequential()
        # m2.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Pool + Dense + Dense
        m2.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 1)))
        m2.add(layers.MaxPooling2D(pool_size=2))
        # m2.add(layers.Flatten())#if it is not flattened, only the last layer can be fed into the dense
        m2.add(layers.Dense(128, activation='relu'))
        m2.add(layers.Dense(128, activation='relu'))
        return m2

    def bulid_m3(self):
        m3 = models.Sequential()
        # m3.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3))) 
        # Conv + Conv + Conv + Pool + Dense + Dense
        m3.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 1)))
        m3.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m3.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m3.add(layers.MaxPooling2D(pool_size=2))
        # m3.add(layers.Flatten())#if it is not flattened, only the last layer can be fed into the dense
        m3.add(layers.Dense(128, activation='relu'))
        m3.add(layers.Dense(128, activation='relu'))
        return m3

    def bulid_m4(self):
        m4 = models.Sequential()
        # m4.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # onv + Pool + Conv + Dense + Dense
        m4.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m4.add(layers.MaxPooling2D(pool_size=2))
        m4.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        # m4.add(layers.Flatten())#if it is not flattened, only the last layer can be fed into the dense
        m4.add(layers.Dense(128, activation='relu'))
        m4.add(layers.Dense(128, activation='relu'))
        return m4

    def bulid_m5(self):
        m5 = models.Sequential()
        # m5.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Globalpool + Dense + Dense
        m5.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m5.add(layers.GlobalMaxPooling2D(data_format=None, keepdims=False))
        # m5.add(layers.Flatten())#if it is not flattened, only the last layer can be fed into the dense
        m5.add(layers.Dense(128, activation='relu'))
        m5.add(layers.Dense(128, activation='relu'))
        return m5

    def bulid_m6(self):
        m6 = models.Sequential()
        # m6.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Conv + Globalpool + Dense + Dense   
        m6.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m6.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m6.add(layers.GlobalMaxPooling2D(data_format=None, keepdims=False))
        # m6.add(layers.Flatten())#if it is not flattened, only the last layer can be fed into the dense
        m6.add(layers.Dense(128, activation='relu'))
        m6.add(layers.Dense(128, activation='sigmoid'))
        return m6

    def bulid_m7(self):
        m7 = models.Sequential()
        # m7.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Pool + Conv + Pool + Dense + Dens
        m7.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m7.add(layers.MaxPooling2D())
        m7.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m7.add(layers.MaxPooling2D())
        m7.add(layers.Dense(128, activation='relu'))
        m7.add(layers.Dense(128, activation='sigmoid'))
        return m7

    def bulid_m8(self):
        m8 = models.Sequential()
        # m8.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        # Conv + Pool + Conv + Pool + Conv + Pool + Dense + Dense
        m8.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m8.add(layers.MaxPooling2D())
        m8.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m8.add(layers.MaxPooling2D())
        m8.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m8.add(layers.MaxPooling2D())
        m8.add(layers.Dense(128, activation='relu'))
        m8.add(layers.Dense(128, activation='sigmoid'))
        return m8

    def bulid_m9(self):
        m9 = models.Sequential()
        # m9.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                             input_shape=(self.image_width, self.image_height, 3)))
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m9.add(layers.MaxPooling2D())
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m9.add(layers.MaxPooling2D())
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m9.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m9.add(layers.MaxPooling2D())
        m9.add(layers.Dense(128, activation='relu'))
        m9.add(layers.Dense(128, activation='relu'))
        m9.add(layers.Dense(128, activation='relu'))
        m9.add(layers.Dense(128, activation='sigmoid'))
        return m9

    def bulid_m10(self):
        m10 = models.Sequential()
        # m10.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu',
                              input_shape=(256,256,1)))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m10.add(layers.MaxPooling2D())
        m10.add(layers.Dropout(.2))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m10.add(layers.MaxPooling2D())
        m10.add(layers.Dropout(.2))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m10.add(layers.Conv2D(16, 3, padding='same', activation='relu'))
        m10.add(layers.MaxPooling2D())
        m10.add(layers.Dropout(.2))
        m10.add(layers.Dense(128, activation='relu'))
        m10.add(layers.Dropout(.2))
        m10.add(layers.Dense(128, activation='relu'))
        m10.add(layers.Dropout(.2))
        m10.add(layers.Dense(128, activation='relu'))
        m10.add(layers.Dropout(.2))
        m10.add(layers.Dense(128, activation='sigmoid'))
        return m10

    def bulid_m11(self):
        ''' the dropout rates of 0.2, 0.3, 0.4 and batch normalization assigned between the convolution-pooling layers of VGG3, also the same added between the three fully connected layers of 4096 neurons each '''
        m11 = models.Sequential()
        #m11.add(layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 1)))

        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu',input_shape=(self.image_width, self.image_height, 1)))
        m11.add(layers.BatchNormalization())

        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.MaxPooling2D())
        m11.add(layers.Dropout(.2))

        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.MaxPooling2D())
        m11.add(layers.Dropout(.3, input_shape=(2,)))

        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Conv2D(32, 3, padding='same', activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.MaxPooling2D())
        m11.add(layers.Dropout(.4, input_shape=(2,)))

        m11.add(layers.Flatten())
        m11.add(layers.Dense(4096, activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Dropout(.2))
        m11.add(layers.Dense(4096, activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Dropout(.3, input_shape=(2,)))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Dense(4096, activation='relu'))
        m11.add(layers.BatchNormalization())
        m11.add(layers.Dropout(.4, input_shape=(2,)))
        m11.add(layers.Dense(2, activation='sigmoid'))
        return m11

    def bulid_m12(self):
        m12 = models.Sequential([
            # layers.experimental.preprocessing.Rescaling(1./255, input_shape=(self.image_width, self.image_height, 3)),
            applications.resnet50.ResNet50(include_top=True, weights='imagenet', input_tensor=None, input_shape=None,
                                           pooling=None, classes=1000),
            layers.Dense(128, activation='relu'),
            layers.Dense(1024, activation='relu'),
            layers.Dense(512, activation='relu'),
            layers.Dense(256, activation='sigmoid'),
        ])
        return m12

    def define_callbacks(self):
        checkpoint_cb = ModelCheckpoint("/content/Model.h5", save_freq="epoch", save_best_only=True)
        early_stopping_cb = EarlyStopping(patience=10, restore_best_weights=True)
        logger_cb = CSVLogger('training.log', separator="|")
        return [checkpoint_cb, early_stopping_cb, logger_cb]

    def train_bb_detector(self,training_set,validation_set):
      
        #uploader = UploadData()
        #training_set, validation_set = uploader.upload_set()
        # binary crossentropy or sparse categorical???
      self.model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
      history = self.model.fit(training_set, epochs=self.epochs, validation_data=validation_set,
                                 callbacks=self.define_callbacks())
      return history

    def plot_history(self):
      data_frame = pandas.DataFrame(self.history.history)
      data_frame.plot(figsize=(7, 3))
      plt.xlabel('Epochs')
      plt.ylabel('Sparse categorical cross-entropy')

    def evaluate_bb_detector(self):
      #uploader = UploadData()
      #test_set = uploader.upload_test_set('/content/dataseett/dataset/test_set')
      validation_set = keras.preprocessing.image_dataset_from_directory(
          self.TEST_DATA_DIRECTORY,
          labels='inferred', 
          label_mode='int',
          class_names=None,
          color_mode=self.COLOR_MODE,
          seed=self.SEED,
          interpolation="area",
          batch_size=self.BATCH_SIZE,
          image_size=(self.IMAGE_HEIGHT, self.IMAGE_WIDTH),
          shuffle=True,
      )
      test_loss, test_acc = self.model.evaluate(test_set, verbose=2)
      print('\nTest accuracy:', test_acc)



In [ ]:
dogs_train

<BatchDataset shapes: ((None, 256, 256, 1), (None,)), types: (tf.float32, tf.int32)>

In [ ]:
mixed_train
          

<BatchDataset shapes: ((None, 256, 256, 1), (None,)), types: (tf.float32, tf.int32)>

In [ ]:
mixed_val

<BatchDataset shapes: ((None, 256, 256, 1), (None,)), types: (tf.float32, tf.int32)>

In [39]:
bb_detector = MalwareDetectionModels(width, height, 'M11',mixed_train, mixed_val)

Epoch 1/5
213/213 [==============================] - 120s 377ms/step - loss: 1.3629 - accuracy: 0.5671 - val_loss: 0.7998 - val_accuracy: 0.6017
Epoch 2/5
213/213 [==============================] - 89s 374ms/step - loss: 0.8182 - accuracy: 0.6240 - val_loss: 1.0868 - val_accuracy: 0.6058
Epoch 3/5
213/213 [==============================] - 89s 373ms/step - loss: 0.7593 - accuracy: 0.6596 - val_loss: 1.3442 - val_accuracy: 0.6150
Epoch 4/5
213/213 [==============================] - 88s 372ms/step - loss: 0.6548 - accuracy: 0.7190 - val_loss: 0.8081 - val_accuracy: 0.6258
Epoch 5/5
213/213 [==============================] - 89s 373ms/step - loss: 0.5784 - accuracy: 0.7554 - val_loss: 0.6911 - val_accuracy: 0.7300


# Master Model

In [56]:
# from Models import MalwareDetectionModels
# from UploadData import UploadData
import tensorflow as tf
import numpy as np
import os
import tensorflow.keras as keras
from tensorflow.keras import layers, models, applications, optimizers, losses, metrics
from keras.layers.merge import Concatenate
from keras import layers
from keras.layers import Input
from keras.models import Model
from IPython import display

class MasterGAN:
    BUFFER_SIZE = 60000
    BATCH_SIZE = 256

    def __init__(self, blackbox, img_w=256, img_h=256):
        # initialize image aspect ratio
        self.img_width = img_w
        self.img_height = img_h
        self.EPOCHS = 50
        self.noise_dim = 256
        
        self.num_examples_to_generate = 16

        # You will reuse this seed overtime (so it's easier)
        # to visualize progress in the animated GIF)
        self.seed = tf.random.normal([self.num_examples_to_generate, self.noise_dim])
        
        self.cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=False)

        ''' add this option???
        self.same_train_data = same_train_data   # MalGAN and the black-boxdetector are trained on same or different training sets
        '''

        

        # load model file, the blackbox detector is trained upon calling the init function.
        # In any case, it is trained externally
        self.blackbox = blackbox
        #self.blackbox_detector = bb_detector
        #self.blackbox_detector = MalwareDetectionModels(self.img_width, self.img_height, self.blackbox)
        #self.bb_detector = MalwareDetectionModels(img_width, img_height, blackbox)


        ####### define GAN #########
        self.substitute_detector_optimizer = tf.keras.optimizers.Adam(lr=1e-5, beta_1=0.1)
        self.generator_optimizer = tf.keras.optimizers.Adam(lr=2e-4, beta_1=0.5)
        self.generator = self.build_generative_model()
        self.substitute_detector = self.build_substitute_detector_model()

        '''###load the dataset####
        uploader = UploadData()
        self.train_mal_set, self.val_mal_set = uploader.upload_train_mal_set()
        self.train_ben_set, self.val_ben_set = uploader.upload_train_ben_set()
        self.test_mal_set = uploader.upload_test_mal_set()
        self.test_ben_set = uploader.upload_test_ben_set()'''


   
    def build_generative_model(self):
        #ref https://www.tensorflow.org/tutorials/generative/pix2pix
        # generator = models.Sequential() # Sequential model is not appropriate when: Your model has multiple inputs
        # or multiple outputs ref: https://keras.io/guides/sequential_model/
        noise_input = Input(shape=(256,self.noise_dim)) #if we want the noise with size 256*256,we can use shape=(noise_dim,self.noise_dim)
        mal_sample_input = Input(shape=(self.img_width,self.img_height))
        final_input = Concatenate(axis = 1)([mal_sample_input, noise_input])
        print(final_input)
        current_output = layers.Dense(32, use_bias=False)(final_input)
        current_output = layers.BatchNormalization()(current_output)
        current_output = layers.LeakyReLU()(current_output)

        current_output = layers.Reshape((32, 32, 16))(current_output)
        # assert current_output.output_shape == (None, 32, 32, 16)  # Note: None is the batch size

        current_output = layers.Conv2DTranspose(8, (5, 5), strides=(2, 2), padding='same', use_bias=False)(
            current_output)
        # assert current_output.output_shape == (None, 64, 64, 8)(current_output)
        current_output = layers.BatchNormalization()(current_output)
        current_output = layers.LeakyReLU()(current_output)

        current_output = layers.Conv2DTranspose(4, (5, 5), strides=(2, 2), padding='same', use_bias=False)(
            current_output)
        # assert current_output.output_shape == (None, 128, 128, 4)
        current_output = layers.BatchNormalization()(current_output)
        current_output = layers.LeakyReLU()(current_output)

        current_output = layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False,
                                                activation='tanh')(current_output)
        # assert current_output.output_shape == (None, 256, 256, 1)
        generator = Model(inputs=[noise_input, mal_sample_input], outputs=[current_output])
        #print(generator.summary())
        tf.keras.utils.plot_model(
            generator,to_file='/content/data/model.png', show_shapes=True, show_dtype=True,
            show_layer_names=True, rankdir='TB', expand_nested=False, dpi=96,
            layer_range=None)
        return generator

    def build_substitute_detector_model(self):

        # it can be a convolutional network which works as a classifier
        substitute_detector = tf.keras.Sequential()
        substitute_detector.add(layers.Conv2D(64, (5, 5), activation='relu', strides=(2, 2), padding='same',
                                              input_shape=[self.img_width, self.img_height, 1]))

        substitute_detector.add(layers.MaxPooling2D(2, 2))

        substitute_detector.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
        substitute_detector.add(layers.Conv2D(128, (5, 5), strides=(5, 5), padding='same'))
        substitute_detector.add(layers.MaxPooling2D(2, 2))

        substitute_detector.add(layers.Flatten())
        substitute_detector.add(layers.Dense(64, activation='relu'))
        substitute_detector.add(layers.Dropout(0.4))
        substitute_detector.add(layers.Dense(32, activation='relu'))
        substitute_detector.add(layers.Dropout(0.3))

        substitute_detector.add(layers.Dense(2, activation='sigmoid'))
        return substitute_detector

    
    def substitute_detector_loss(self, sd_on_real, sd_on_adv, bb_on_real, bb_on_adv):
        # the loss for the discriminator is computed as the sum of the loss related to real samples not being
        # classified correctly and the loss related to generated samples not being classified correctly
        real_loss = self.cross_entropy(bb_on_real, sd_on_real)
        fake_loss = self.cross_entropy(bb_on_adv, sd_on_adv)
        total_loss = real_loss + fake_loss
        return total_loss

    def generator_loss(self, sd_on_adv):
        return self.cross_entropy(tf.ones_like(sd_on_adv), sd_on_adv)

    def checkpoint(self):
      checkpoint_dir = '/content/sample_data/'
      checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
      checkpoint = tf.train.Checkpoint(generator_optimizer=self.generator_optimizer,
                                      substitute_detector_optimizer=self.substitute_detector_optimizer,
                                      generator=self.generator,
                                      discriminator=self.substitute_detector)
      return checkpoint,checkpoint_prefix
    # Notice the use of `tf.function`
    # This annotation causes the function to be "compiled".
    @tf.function
    def train_step(self,batch_mal, batch_ben):
        # in redefining how the function .fit() behaves for a model, the train_step(self,data) function needs to be
        # overridden ref https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit
        img_batch_mal, lbls_mal = batch_mal
        img_batch_ben, lbls_ben = batch_ben
        img_nums= len(lbls_mal)
        new_noise = tf.random.normal([img_nums,self.img_width, self.img_height])
   

        ''' "TensorFlow provides the tf.GradientTape API for automatic differentiation; 
                that is, computing the gradient of a computation with respect to some inputs, 
                usually tf.Variables. TensorFlow "records" relevant operations executed inside 
                the context of a tf.GradientTape onto a "tape". TensorFlow then uses that tape 
                to compute the gradients of a "recorded" computation using reverse mode differentiation."'''
        with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
            # with each step the generator produces a set of images
            
            adv_malware_samples = self.generator([new_noise,img_batch_mal], training=True)

            # the discriminator makes predictions on real images first, then on adversarial samples. Each prediction
            # is stored into a variable and used to evaluate the discriminator loss
            bb_on_real = self.blackbox.model(img_batch_ben)
            sd_on_real = self.substitute_detector(img_batch_ben, training=True)
            bb_on_adv = self.blackbox.model(adv_malware_samples)
            sd_on_adv = self.substitute_detector(adv_malware_samples, training=True)

            gen_loss = self.generator_loss(sd_on_adv)
            disc_loss = self.substitute_detector_loss(sd_on_real, sd_on_adv, bb_on_real, bb_on_adv)

        gradients_of_generator = gen_tape.gradient(gen_loss, self.generator.trainable_variables)
        gradients_of_sub_detector = disc_tape.gradient(disc_loss, self.substitute_detector.trainable_variables)

        self.generator_optimizer.apply_gradients(zip(gradients_of_generator, self.generator.trainable_variables))
        self.substitute_detector_optimizer.apply_gradients(
            zip(gradients_of_sub_detector, self.substitute_detector.trainable_variables))
    
    def train(self,ben_images, mal_images,test_mal_set):
      ckpt,ckpt_prefix = self.checkpoint()
      for epoch in range(self.EPOCHS):
        start = time.time()
        for batch_mal,batch_ben in zip(mal_images,ben_images):

          self.train_step(batch_mal,batch_ben)
        '''
        # Produce images for the GIF as you go
        display.clear_output(wait=True)
        self.generate_and_save_images(self.generator,epoch + 1,test_mal_set,self.seed)
                                

        # Save the model every 15 epochs
        if (epoch + 1) % 15 == 0:
          ckpt.save(file_prefix = ckpt_prefix)

        print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

      # Generate after the final epoch
      display.clear_output(wait=True)
      self.generate_and_save_images(self.generator,self.EPOCHS,test_mal_set,self.seed)'''
                              
                              

    def generate_and_save_images(self, generator, epoch, test_mal_set,noise):
      # Notice `training` is set to False.
      # This is so all layers run in inference mode (batchnorm).
      
      predictions = generator([test_mal_set,noise], training=False)

      fig = plt.figure(figsize=(4, 4))

      for i in range(predictions.shape[0]):
          plt.subplot(4, 4, i+1)
          plt.imshow(predictions[i, :, :, 0] * 127.5 + 127.5, cmap='gray')
          plt.axis('off')

      plt.savefig('image_at_epoch_{:04d}.png'.format(epoch))
      plt.show()
    
    '''def __main__():
      ###load the dataset####
      uploader = UploadData()
      train_mal_set, self.val_mal_set = uploader.upload_train_mal_set()
      train_ben_set, self.val_ben_set = uploader.upload_train_ben_set()
      test_mal_set = uploader.upload_test_mal_set()
      test_ben_set = uploader.upload_test_ben_set()
      train(train_)'''


In [57]:
GAN = MasterGAN(bb_detector,256, 256)
GAN.train(dogs_train,cats_train,cats_test)


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


KerasTensor(type_spec=TensorSpec(shape=(None, 512, 256), dtype=tf.float32, name=None), name='concatenate_8/concat:0', description="created by layer 'concatenate_8'")


KeyboardInterrupt: ignored